image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore
  # Redis
  - port: 6379
    onOpen: ignore
  # PGSQL server
  - port: 6864
    onOpen: ignore

tasks:
  - init: >
      mysql -u root -e "create database laravel" &&
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      npm install --global npm@latest &&
      composer install &&
      npm install &&
      npm run dev &&
      php artisan migrate:fresh --seed &&
      php artisan key:generate &&
      php artisan serve
    command: >
      php -S 0.0.0.0:8000 -t public
    
